[phases.setup]
nixPkgs = ["nodejs_22", "python3", "pkg-config", "gcc"]

[phases.install]
cmds = ["corepack enable && pnpm install"]

[phases.build]
cmds = [
  "pnpm --filter client build",
  "cd server && node_modules/.bin/tsc"
]

[start]
cmd = "node server/dist/server/index.js"
